owner: Community-Lores
repo: status-page
sites:
  - name: Homepage
    url: https://community-lores.gq
status-website:
  cname: status.community-lores.gq
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Community Lores Infrastructure Status Page
  introTitle: "T"
  introMessage: We continuously monitor Community Lores-hosted websites/wikis and related infrastruture. If something goes wrong, an update will be posted here.
  navbar:
    - title: Status
      href: /
    - title: Source
      href: https://github.com/$OWNER/$REPO
    - title: GitLab
      href: https://gitlab.com/$OWNER
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
